# Generated by Django 4.2.1 on 2023-05-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corgi',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
